### ISSUE TITLE
collided paths

### ISSUE THREAD

**Issue by SamuelMarks** [Fantom-foundation/jlachesis#1]
By default, Mac—and somewhat Windows—have case insensitive file systems:

```
$ git clone https://github.com/Fantom-foundation/jlachesis
Cloning into 'jlachesis'...
remote: Enumerating objects: 202, done.
remote: Counting objects: 100% (202/202), done.
remote: Compressing objects: 100% (178/178), done.
remote: Total 202 (delta 12), reused 202 (delta 12), pack-reused 0
Receiving objects: 100% (202/202), 186.95 KiB | 330.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'src/main/java/node/NodeState.java'
  'src/main/java/node/nodeState.java'
```

**Comment by quannguyenh** [comment]
Conversion from go code. It's minor. Code will be refactored later.

Dont have that issue on Ubuntu.

$ git clone https://github.com/Fantom-foundation/jlachesis
Cloning into 'jlachesis'...
remote: Enumerating objects: 345, done.
remote: Counting objects: 100% (345/345), done.
remote: Compressing objects: 100% (236/236), done.
remote: Total 345 (delta 100), reused 321 (delta 76), pack-reused 0
Receiving objects: 100% (345/345), 255.47 KiB | 174.00 KiB/s, done.
Resolving deltas: 100% (100/100), done.

**Comment by quan8** [comment]
Hi Sam, I guess this issue was fixed. Thanks.
